language: dart
os:
  - linux
sudo: false
dart:
  - stable
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - cd hive_flutter
  - ./flutter/bin/flutter packages pub get
  - ./flutter/bin/flutter test
  - cd ../hive_generator
  - pub get
  - pub run test
  - cd ../hive
  - pub get
  - pub run test -p "vm,chrome"
  - dartfmt -n --set-exit-if-changed ./lib ./test ./example || travis_terminate 1
  - pub global activate test_coverage
  - test_coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
