language: dart
os:
  - linux
sudo: false
dart:
  - stable
script:
  - cd ../hive_generator
  - pub get
  - pub run test

  - cd ../hive
  - pub get
  - pub run test -p "vm,chrome"
  
  - dartfmt -n --set-exit-if-changed ./lib ./test ./example || travis_terminate 1
  
  - pub global activate test_coverage
  - test_coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
