name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 0.2.1
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/hive

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
